### ISSUE TITLE
File or Directory does not exist

### ISSUE THREAD

**Issue by XPLegend** [odziom91/libadwaita-theme-changer#6]
`chmod: could not access 'libadwaita-tc.py': File o directory does not exist`

It keeps giving me this error, what should I do?

**Comment by odziom91** [comment]
Are you sure that you are in directory where libadwaita-tc.py exists? ;)

**Comment by XPLegend** [comment]
> Are you sure that you are in directory where libadwaita-tc.py exists? ;)

Ohhh, I am feeling very stupid, very very stupid, thank you!! 😅
